# Generated by Django 2.2.16 on 2020-11-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Name')),
                ('precio', models.FloatField(default=0, verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Date')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Infrastructure amount')),
                ('articulos', models.ManyToManyField(related_name='pedido', to='bernini.Articulo', verbose_name='articulos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bernini.Cliente')),
            ],
        ),
    ]
