# Generated by Django 2.2.16 on 2020-11-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bernini', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='articulos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precio',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.CreateModel(
            name='Pedido_Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_articulo', to='bernini.Articulo', verbose_name='Articulo')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_articulo', to='bernini.Pedido', verbose_name='Articulo')),
            ],
        ),
    ]
